# Generated by Django 4.2.11 on 2024-04-01 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='address',
            field=models.CharField(default='Biratnagar', max_length=255),
            preserve_default=False,
        ),
    ]
