# Generated by Django 4.2.11 on 2024-04-01 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_person_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='phone',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
